spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url:  jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000

app:
  redis:
    enable: true
  cache:
    cacheTypes: redis
    cache-names:
      - bookByNameAndAuthor
      - listBookByCategoryName
    caches:
      bookByNameAndAuthor:
        expiry: 10m
      listBookByCategoryName:
        expiry: 10m




